language: node_js
node_js:
  - '10.13.0'
cache: yarn

jobs:
  include:
    - name: 'Type Check'
      script:
        - yarn run type-check

    - name: 'Lint'
      script:
        - yarn run lint

    - name: 'Unit Tests'
      script:
        - yarn run test --coverage
        - yarn run codecov

    - name: 'Shrink Ray'
      script:
        - yarn run storybook:build --quiet
        - yarn run shrink-ray build --report-path="build/storybook/bundle-analysis/report.html" --repo="polaris-react" --sha="$TRAVIS_COMMIT" --baselineSha="$(git merge-base HEAD origin/master)"

    - name: 'Percy'
      script:
        - yarn run storybook:build --quiet
        - yarn run percy-storybook --build_dir="build/storybook/static"

    - name: 'Chroma'
      script:
        - yarn run chromatic publish --build-script-name='storybook:build'

    - name: 'Accessibility Tests'
      script:
        - yarn run storybook:build --quiet
        - node ./scripts/pa11y.js
